- src/lib.rs
While using ByteSize, I noticed that ByteSize values have a sensible default value: 0 Bytes. This would allow struct containing ByteSize values to derive(Default) as well.
Adds derive(Default) and a test.
> Implement Default trait

- Cargo.toml
- src/lib.rs
This PR adds an optional cargo feature that adds `serde` support. This is essentially implemented in the manner suggested by the [Rust API guidelines](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde)
> Add optional serde support

- src/lib.rs
This makes sure that when formatted with `Display` the `ByteSize` struct can be aligned correctly.
See the tests for examples.
> feat: impl padding for Display trait for ByteSize

- src/lib.rs
Currently there is no way to create a global constant of `ByteSize`.
This PR should add that feature.
```rust
const MEMORY_LIMIT2: ByteSize = ByteSize::mb(512);
```
> It would be great if we were to allow creating ByteSize constants

- src/lib.rs
- src/parse.rs
A use case I came around when I wanted the user to provide a ByteSize in my program CLI arguments and using a argument parser like structopt or argh or gumdrop.
Allows parsing a string directly into a ByteSize:
```rust
let size = "128GB".parse::<ByteSize>().unwrap();
```
I'm bad at writing negative test cases though.
Short example of a binary using structopt taking a size as a command line argument:
```rust
use bytesize::ByteSize;
use structopt::StructOpt;
#[derive(Debug, StructOpt)]
struct Args {
size: ByteSize,
}
fn main() {
println!("{}", Args::from_args().size);
}
```
PS: the two `'static` lifetime markers I removed because of clippy's suggestion
> Implement the FromStr trait for ByteSize

- src/lib.rs
While using `ByteSize`, I found out that I was missing `AddAssign` operator.
This pr should allow the following
```rust
let mut x = ByteSize::mb(1);
let y = ByteSize::mb(1);
x += y;
```
> add AddAssign operator to ByteSize

- .gitignore
- Cargo.toml
- src/lib.rs
- src/parse.rs
- adds serde human readable bytesize support
- fixes several clippy warnings with u16/u8 and is_digit/is_ascii_digit
resolves #27
> serde improvements

- src/parse.rs
Hi @hyunsik 
Thank you for developing such a great crate!
I wanted to contribute to this crate in any way I could, so I made some changes to improve performance.
This change also helps support no_std in issue #3
> Improved performance by eliminating String creation by utilizing the original &str slice.

- Cargo.toml
- src/lib.rs
ByteSize does not currently support deriving `Arbitrary`, which is needed to perform fuzz testing. This patch adds a feature flag that, when enabled, will derive `Arbitrary` for `ByteSize`. `cargo fmt` also updated a few lines.
Please see https://rust-fuzz.github.io/book/cargo-fuzz.html for information regarding fuzz testing. More specifically, https://rust-fuzz.github.io/book/cargo-fuzz/structure-aware-fuzzing.html provides information on `Arbitrary`.
> Integrate Arbitrary Feature

- src/lib.rs
Hi @hyunsik 
I modified the ByteSize::to_string in the documentation comment to match the currently available APIs so that the tests can run.
I thought that the other subtraction operation example should also be modified to match the current API, but should I remove the subtraction example or implement subtraction on ByteSize? I couldn't fix it because I couldn't judge it. If you have a clear answer on which one to do, I would like to fix it and create a new PR.
> Make testable about ByteSize::to_string_as in doc example

- .github/workflows/rust.yml
- CHANGELOG
- CHANGELOG.md
- Cargo.toml
- Makefile
- README.md
- src/lib.rs
- Use SI format by default with Display.
- Use "KiB" for SI unit.
- Bump to version 2.
#49
> feat: merge foyer-rs/bytesize back to the OG repo

- src/lib.rs
> test: add unit test for json serde

- CHANGELOG.md
- src/lib.rs
> feat: impl Sub and SubAssign for bytesize

- .prettierrc.yml
- README.md
- justfile
- src/lib.rs
if anyone wants deleted items from the readme to be returned, no problem, they'll just need to go in lib.rs now... i'm just trying to move this boring piece forward for the sake of other PRs
> docs: use cargo-rdme to match readme to tested docs

- examples/ls.rs
can be used as a test case for #14
```
cargo run --example=ls | sort -h
```
> docs: add ls example

- CHANGELOG.md
- Cargo.toml
- src/lib.rs
- src/parse.rs
- src/serde.rs
rebase and follow on from #38 
Fixes https://github.com/bytesize-rs/bytesize/issues/25
Fixes https://github.com/bytesize-rs/bytesize/issues/26
Fixed https://github.com/bytesize-rs/bytesize/issues/37
> fix inverted SI / IEC conditions

- CHANGELOG.md
- src/lib.rs
the boolean parameter on this for IEC/SI selection is non-obvious
... instead we'll pursue something like #32 or #76
> chore: remove to_string_as method

- Cargo.lock
- Cargo.toml
- benches/display.rs
- examples/ls.rs
- justfile
- src/display.rs
- src/lib.rs
- src/parse.rs
waiting for #71
similar to #32
> feat: display type

- src/display.rs
Updated the documentation to match the actual code behavior.
```rust
use bytesize::ByteSize;
fn main() {
let foo = ByteSize(12345678);
println!("Default   {}", foo);
println!("iec       {}", foo.display().iec());
println!("iec_short {}", foo.display().iec_short());
println!("si        {}", foo.display().si());
println!("si_short  {}", foo.display().si_short());
}
```
```
Default   11.8 MiB
iec       11.8 MiB
iec_short 11.8M
si        12.3 MB
si_short  12.3M
```
I arbitrarily changed the numbers to make the difference more noticeable, but feel free to adjust them if there are better values to express it.
> Fix: Corrected Display unit mismatch.

- Cargo.toml
I've noticed, that there is no MSRV specified for `1.x`-versions of this crate, which is unfortunate, as this prevents the MSRV-aware resolver of Cargo 1.84+ to check, whether the crate is available or not. Therefore this commit adds the missing meta-data.
I've selected Rust 1.61, since this is the lowest version, where `cargo build --features=serde` is successful:
```console
$ cargo +1.61 build --features=serde
Compiling proc-macro2 v1.0.94
Compiling unicode-ident v1.0.18
Compiling serde v1.0.219
Compiling quote v1.0.40
Compiling syn v2.0.100
Compiling serde_derive v1.0.219
Compiling bytesize v1.3.0 (/home/jfrimmel/git/bytesize)
Finished dev [unoptimized + debuginfo] target(s) in 7.27s
```
> Add MSRV-version to for `1.x` release track

- Cargo.toml
This makes it easier to look up e.g. the `serde` trait impls using the “source” links in the documentation.
> Configure docs.rs to build with all features
